config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, sign_out_via: [:get, :post]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  post 'authenticate', to: 'authentication#authenticate'

  resources :users do
    resources :posts
  end

  resources :posts do
    resources :comments
    resources :likes
  end

  namespace :api do
    resources :users do 
      resources :posts 
    end 
    resources :posts do
       resources :comments 
       resources :likes 
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, dependent: :destroy, foreign_key: 'author_id'
  has_many :likes, dependent: :destroy, foreign_key: 'author_id'
  has_many :comments, dependent: :destroy, foreign_key: 'author_id'

  after_initialize :init

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end

  private

  def init
    self.posts_counter ||= 0
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  # before_action :authenticate_request
  def index
    @users = User.all
    render json: @users, status: :ok
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div>
  <h1>List of Users</h1>
  <ul class="list-group">
    <% @users.each do |user| %>
      <li class="list-group-item">
        <div class="d-flex align-items-center justify-content-between">
          <div style="width: 120px;">
            <img src=<%= user.photo %> class="img-thumbnail"/>
          </div>
            <h2><%= link_to user.name, user_path(user) %></h2>
            <p>Number of posts: <%= user.posts_counter %></p>
        </div>
      </li>
    <%end%>
  </ul>
</div>

app/views/users/show.html.erb
<div>
  <h1>User Details by <%= @user.name %> (<%= @user.id %>)</h1>

  <div class="d-flex align-items-center">
    <div class="w-25" style="width: 120px;">
      <img src=<%= @user.photo %> class="img-thumbnail"/>
    </div>
    <div class="w-25">
      <h2><%= @user.name %></h2>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
    <div>
      <h2>Bio: </h2>
      <p><%= @user.bio %> </p>
    </div>
  </div>

  <div class="mt-2 d-flex justify-content-end">
    <% if current_user.id == @user.id %>
      <%= link_to "Add New Post", "/users/#{@user.id}/posts/new", class: "btn btn-primary" %>
    <% end %>
    <%= link_to "See all posts", user_posts_path(@user), class:"btn btn-secondary" %>
  </div>

  <div class="mt-3">
    <ul>
      <% @user.recent_posts.each do |post| %>
        <li class="card mt-2">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h3><%= link_to post.title, user_post_path(@user.id, post) %></h3>
            <div class="d-flex">
              Comments: <%= post.comments_counter%>
              Likes: <%= post.likes_counter%>
              <% if can? :destroy, post%>
              <%= form_with url: "/users/#{@user.id}/posts/#{post.id}" , method: :delete do |f|%>
                <%= f.submit 'Delete Post', class: 'btn btn-sm btn-danger' %>
              <%end%>
            <%end%>
            </div>
          </div>
          <div class="card-body">
            <p><%= post.text%></p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

</div>